version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodatabase
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root